version: '3'
services:

  lenses:
    image: lensesio/box
    container_name: lenses
    restart: always
    environment:
      EULA: "${LICENSE}"
    networks:
      - lenses
    ports:
      - 3030:3030

  vault:
    image: vault
    container_name: vault
    restart: always
    networks:
      - lenses
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:1234
    ports:
     - 1234:1234
     - 8200:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    volumes:
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config

networks:
  lenses:
    driver: bridge
