version: '3'
services:

  lenses:
    image: lensesio/box
    container_name: lenses
    restart: always
    environment:
      EULA: "${LICENSE}"
    networks:
      - lenses-box
    ports:
      - 3030:3030

networks:
  lenses-box:
    driver: bridge

